### ISSUE TITLE
Instructions need to be updated for manual install

### ISSUE THREAD

**Issue by toymachiner62** [dracula/zsh#11]
I tried following your instructions from [here]() for manually installing the dracula theme, but when followed exactly, you get this error:

```sh
Last login: Tue Jul  9 14:33:21 on ttys001
/Users/tomcaflisch/.oh-my-zsh/themes/dracula.zsh-theme:source:15: no such file or directory: /Users/tomcaflisch/.oh-my-zsh/themes/lib/async.zsh
/Users/tomcaflisch/.oh-my-zsh/themes/dracula.zsh-theme:18: command not found: async_init
dracula_git_async:1: command not found: async_start_worker                                                                                  
dracula_git_async:2: command not found: async_register_callback
dracula_git_async:3: command not found: async_job
➜ ~ 
```

I figured out that I also needed to copy the `/lib` folder into my `$OH_MY_ZSH/themes/` folder as well.

I'd submit a PR, but not sure where the repo/branch is for https://draculatheme.com/zsh/

**Comment by Glennmen** [comment]
You can find the install pages here if you still want to make a PR: https://github.com/dracula/dracula.github.io

**Comment by toymachiner62** [comment]
PR submitted.

**Comment by yzgyyang** [comment]
+1 also encountered this error. Please merge the PR, thanks!

**Comment by dinhlongviolin1** [comment]
Thank alot, finally got it to work 👍

**Comment by hacknug** [comment]
I'm leaving this open to make sure everyone finds the issue.

I've merged the PR but right now the site's not can't be re-built and it might take a while until we fix it (I already talked to Zeno about this and we'll probably fix it soon-ish™).

**Comment by ribeirojose** [comment]
The instructions are still not up to date at https://draculatheme.com/zsh/, and I couldn't find if this site is generated using an open-source repo. Should I create a new issue?

**Comment by hacknug** [comment]
@ribeirojose I literally answered to your question in the previous comment haha

**Comment by ribeirojose** [comment]
Ops. Sorry about that!

**Comment by zrfrank** [comment]
Also for oh-my-zsh, manually, its easier if you clone the theme into&as
`~/.oh-my-zsh/custom/theme/dracula`. 
Then in `.zshrc` set `ZSH_THEME="dracula/dracula"`

**Comment by AGitBoy** [comment]
The site is finally updated with the correct information. I am closing this issue now.

**Comment by icebarf** [comment]
Commenting here as the issue seems to be still present. Dated 11/13/21.

Getting the same errors as mentioned above.
```bash
/home/icebarf/.oh-my-zsh/themes/dracula.zsh-theme:source:15: no such file or directory: /home/icebarf/.oh-my-zsh/themes/lib/async.zsh
/home/icebarf/.oh-my-zsh/themes/dracula.zsh-theme:18: command not found: async_init
dracula_git_async:1: command not found: async_start_worker
dracula_git_async:2: command not found: async_register_callback
dracula_git_async:3: command not found: async_job
```

**Comment by LrnzDC3696** [comment]
the fix is still not upto date with the site July, 18, 2022.

**Comment by themegabyte** [comment]
Quickest fix I saw was:

```bash
cd $ZSH_CUSTOM/themes
git clone https://github.com/dracula/zsh.git
```
in `~/.zshrc` 
```bash
ZSH_THEME="dracula/dracula"
```

Thank you @zrfrank

**Comment by ronnyandre** [comment]
I got error `[oh-my-zsh] theme 'dracula/dracula' not found`, so for the ones trying @themegabyte solution above, do this:

```bash
cd $ZSH_CUSTOM/themes
git clone https://github.com/dracula/zsh.git dracula
```

**Comment by Arokota** [comment]
I also found this issue after the website installation instructions failed and generated similar errors to the previous comments. @themegabyte's solution solved my problem for anyone else that finds this,

**Comment by fhoekstra** [comment]
Thanks for your instructions @themegabyte @ronnyandre !

I've put in an attempt to get these instructions onto the site: https://github.com/dracula/draculatheme.com/pull/251
